### ISSUE TITLE
Windows suddenly claims it's a trojan

### ISSUE THREAD

**Issue by fgsfdsfgts** [qubic-li/client#105]
It randomly stopped mining and then I wasted my life for an entire day trying to figure out how to even get anything but a blank screen when opening Windows Security (setting the AllowUserUIAccess registry key to 1 was the only thing that worked for me). I thought I had security checks disabled or at least I removed the threat from quarantine months ago and it was working until now. Is this a false positive or what?

General error: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\fgs\Downloads\qli-Client-1.9.7-Windows-x64\qli-runner.exe'(Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\fgs\Downloads\qli-Client-1.9.7-Windows-x64\qli-runner.exe')

System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\fgs\Downloads\qli-Client-1.9.7-Windows-x64\qli-runner.exe'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.File.OpenHandle(String, FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.File.ReadAllBytes(String)
   at li.qubic.trainer.Trainer.CheckTrainerBinary()
   at li.qubic.trainer.Trainer.StartLocalMining()
   at li.qubic.trainer.Trainer.CheckLocalTrainer()
   at li.qubic.trainer.Trainer.Start()
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.File.OpenHandle(String, FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.File.ReadAllBytes(String)
   at li.qubic.trainer.Trainer.CheckTrainerBinary()
   at li.qubic.trainer.Trainer.StartLocalMining()
   at li.qubic.trainer.Trainer.CheckLocalTrainer()
   at li.qubic.trainer.Trainer.Start()
   
   Detected: Trojan:Win64/Malgent!MSR
   ...
   Affected items:
   containerfile: C:\Users\fgs\Downloads\qli-Client-1.9.7-Windows-x64\qli-runner.exe.lock
   file: C:\Users\fgs\Downloads\qli-Client-1.9.7-Windows-x64\qli-runner.exe
   file: C:\Users\fgs\Downloads\qli-Client-1.9.7-Windows-x64\qli-runner.exe.lock->[Base64]->(Base64)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin64%2FMalgent!MSR&threatid=2147782947

**Comment by cdnbum88** [comment]
I had the same thing happen a couple of times. All virus stuff was off. I had to go in virus protection and restore the severe threat and then it worked. But out of the blue on a couple of my rigs. I even did a complete windows install on one. Very annoying. Would like to know how it happened and how to avoid or get rid of.
