### ISSUE TITLE
General error: Could not find file 

### ISSUE THREAD

**Issue by nyamo9922** [qubic-li/client#109]
2024-09-11 13:30:09     ERROR   General error: Could not find file 'C:\Users\hard8\OneDrive\デスクトップ\Qubic Mining\qli-Client-2.2.1-Windows-x64\qli-runner.exe'.(Could not find file 'C:\Users\hard8\OneDrive\デスクトップ\Qubic Mining\qli-Client-2.2.1-Windows-x64\qli-runner.exe'.)

System.IO.FileNotFoundException: Could not find file 'C:\Users\hard8\OneDrive\デスクトップ\Qubic Mining\qli-Client-2.2.1-Windows-x64\qli-runner.exe'.
File name: 'C:\Users\hard8\OneDrive\デスクトップ\Qubic Mining\qli-Client-2.2.1-Windows-x64\qli-runner.exe'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.File.ReadAllBytes(String path)
   at ␦.()
   at ␦.()
   at ␦.()
   at ␦.()
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.File.ReadAllBytes(String path)
   at ␦.()
   at ␦.()
   at ␦.()
   at ␦.()
2024-09-11 13:30:09     INFO    Waiting for task (0)
2024-09-11 13:30:09     INFO    Calculating Checksum (Task/16)

**Comment by nyamo9922** [comment]
I just started CPU mining, but it is not working. I did not move the downloaded exe file, but it does not run the program.

**Comment by nyamo9922** [comment]
Never mind, it is working now.

**Comment by tz222222** [comment]
May I ask how you debugged it and it worked properly? Thank you for your guidance.
