### ISSUE TITLE
GLIBC Error

### ISSUE THREAD

**Issue by UfoX-78** [qubic-li/client#13]
Hi

I have this error : 

023-12-12 21:20:17     ERROR   Looks like the trainer isn't working properly :( check your config and he requirements.
2023-12-12 21:20:17     ERROR   GLIBC Version must by >= 2.34
2023-12-12 21:20:17     ERROR   General error: FATAL: GLIBC Version must by >= 2.34. Trainer can't be started properly.(FATAL: GLIBC Version must by >= 2.34. Trainer can't be started properly.)

Perhaps my verison of glibc is 2.35
ufox@rig-pincab:~/qubic$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.5) 2.35

Thanks

**Comment by jbutko** [comment]
You probably need to upgrade your ubuntu OS version. GLIBC is core lib of unix systems and comes in various versions for each ubuntu version. As far as I know it could not be upgraded via apt, only on full OS upgrade.

**Comment by NiccoBDX** [comment]
Hello, same problem for me:

System.Exception: FATAL: GLIBC Version must by >= 2.34. Trainer can't be started properly.
    at li.qubic.trainer.Trainer.CheckLocalTrainer()
    at li.qubic.trainer.Trainer.Start()
    at li.qubic.trainer.Trainer.CheckLocalTrainer()
    at li.qubic.trainer.Trainer.Start()
2023-12-21 10:25:02 ERROR Looks like the trainer isn't working properly :( check your config and he requirements.
2023-12-21 10:25:02 ERROR GLIBC Version must by >= 2.34
2023-12-21 10:25:02 ERROR General error: FATAL: GLIBC Version must by >= 2.34. Trainer can't be started properly.(FATAL: GLIBC Version must by >= 2.34. Trainer can't be started properly.)

Newly installed Ubuntu 22.04.3 LTS version.
Installed version GLIBC 2.35 (that of 04.22.3)

**Comment by UfoX-78** [comment]
has anyone found a solution for this problem?

I tried the latest version but I still have the same problem.

**Comment by dithink** [comment]
> has anyone found a solution for this problem?
> 
> I tried the latest version but I still have the same problem.

```
sudo apt update
sudo apt upgrade
```

then check the version of GLIBC
`ldd --version
`
because GLIBC 2.35 include in the latest release 22.04.3 LTS

and then please remove qli and reinstall it
