### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ZenoMastro** [qubic-li/client#34]
2024-03-06 00:43:37	ERROR	Execution stopped(FATAL: Please do not use accessToken AND payoutID)

System.Exception: FATAL: Please do not use accessToken AND payoutID
   at li.qubic.trainer.Trainer.VerifyStartup()
   at li.qubic.trainer.Trainer..ctor(String token)
   at Program.Main(String[] args)
   at li.qubic.trainer.Trainer.VerifyStartup()
   at li.qubic.trainer.Trainer..ctor(String token)
   at Program.Main(String[] args)
2024-03-06 00:46:27	ERROR	Looks like the trainer isn't working properly :( check your config and he requirements.
2024-03-06 00:46:27	ERROR	General error: An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.(An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.)

System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at li.qubic.trainer.Helper.HardwareHelper.GetLibcVersion()
   at li.qubic.trainer.Trainer.CheckLocalTrainer()
   at li.qubic.trainer.Trainer.Start()
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at li.qubic.trainer.Helper.HardwareHelper.GetLibcVersion()
   at li.qubic.trainer.Trainer.CheckLocalTrainer()
   at li.qubic.trainer.Trainer.Start()
2024-03-06 00:47:28	ERROR	Looks like the trainer isn't working properly :( check your config and he requirements.
2024-03-06 00:47:28	ERROR	General error: An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.(An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.)

System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at li.qubic.trainer.Helper.HardwareHelper.GetLibcVersion()
   at li.qubic.trainer.Trainer.CheckLocalTrainer()
   at li.qubic.trainer.Trainer.Start()
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at li.qubic.trainer.Helper.HardwareHelper.GetLibcVersion()
   at li.qubic.trainer.Trainer.CheckLocalTrainer()
   at li.qubic.trainer.Trainer.Start()
2024-03-06 00:48:29	ERROR	Looks like the trainer isn't working properly :( check your config and he requirements.
2024-03-06 00:48:29	ERROR	General error: An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.(An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.)

System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'ldd' with working directory 'C:\Users\rosar\Downloads\qli-Client-1.8.5-Windows-x64'. Impossibile trovare il file specificato.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at li.qubic.trainer.Helper.HardwareHelper.GetLibcVersion()
   at li.qubic.trainer.Trainer.CheckLocalTrainer()
   at li.qubic.trainer.Trainer.Start()
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo)
   at li.qubic.trainer.Helper.HardwareHelper.GetLibcVersion()
   at li.qubic.trainer.Trainer.CheckLocalTrainer()
   at li.qubic.trainer.Trainer.Start()

**Comment by MaximKiselev** [comment]
@ZenoMastro, dont use acesstoken together with payoutid. basically, ldd is linux...its weird that tool tried to launch it... need something wmi.

**Comment by J0ET0M** [comment]
ldd has been removed from windows in 1.8.9
