### ISSUE TITLE
Windows 11 Errore

### ISSUE THREAD

**Issue by satruxag** [qubic-li/client#5]
` at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError , String )
   at System.Net.Sockets.Socket.Accept()
   at System.Net.Sockets.TcpListener.AcceptTcpClient()
   at li.qubic.trainer.Comm.ComConnector.<StartServer>b__11_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
--- End of stack trace from previous location ---
   at li.qubic.trainer.Comm.ComConnector.StartServer()
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError , String )
   at System.Net.Sockets.Socket.Accept()
   at System.Net.Sockets.TcpListener.AcceptTcpClient()
   at li.qubic.trainer.Comm.ComConnector.<StartServer>b__11_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
--- End of stack trace from previous location ---
   at li.qubic.trainer.Comm.ComConnector.StartServer()
2023-11-23 12:47:47     ERROR   Looks like the trainer isn't working properly :( check your config.`

this is my conf

{
  "Settings": {
    "baseUrl": "https://ai.diyschool.ch/",
    "amountOfThreads": 32,
    "payoutId": null,
    "accessToken": "<TOKEN>",
    "alias": "<ALIAS>"
  }
}

I have 4 servers, on two it works correctly, while on the others it doesn't. What could it be?

**Comment by wanghaoqd** [comment]
> ` at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError , String ) at System.Net.Sockets.Socket.Accept() at System.Net.Sockets.TcpListener.AcceptTcpClient() at li.qubic.trainer.Comm.ComConnector.<StartServer>b__11_0() at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object ) --- End of stack trace from previous location --- at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread ) --- End of stack trace from previous location --- at li.qubic.trainer.Comm.ComConnector.StartServer() at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError , String ) at System.Net.Sockets.Socket.Accept() at System.Net.Sockets.TcpListener.AcceptTcpClient() at li.qubic.trainer.Comm.ComConnector.<StartServer>b__11_0() at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object ) --- End of stack trace from previous location --- at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread ) --- End of stack trace from previous location --- at li.qubic.trainer.Comm.ComConnector.StartServer() 2023-11-23 12:47:47 ERROR Looks like the trainer isn't working properly :( check your config.`
> 
> this is my conf
> 
> { "Settings": { "baseUrl": "https://ai.diyschool.ch/", "amountOfThreads": 32, "payoutId": null, "accessToken": "", "alias": "" } }
> 
> I have 4 servers, on two it works correctly, while on the others it doesn't. What could it be?

I guess it's because this app relies on AVX2.
