### ISSUE TITLE
INFO Starting Client 1.8.9.0 System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.

### ISSUE THREAD

**Issue by SevenXP** [qubic-li/client#52]
2024-03-17 08:43:32 INFO Starting Client 1.8.9.0
2024-03-17 08:43:32 INFO Check for updates
2024-03-17 08:43:32 INFO Your Client is up to date
System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
---> System.TypeLoadException
at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(IntPtr, Type)
at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](https://github.com/qubic-li/client/issues/IntPtr)
at System.Management.WmiNetUtilsHelper.LoadDelegate[TDelegate](TDelegate&, IntPtr, String)
at System.Management.WmiNetUtilsHelper..cctor()
--- End of inner exception stack trace ---
at System.Management.MTAHelper.IsNoContextMTA()
at System.Management.MTAHelper.CreateInMTA(Type)
at System.Management.ManagementPath.CreateWbemPath(String)
at li.qubic.trainer.Helper.HardwareHelper.GetCPUCacheWindows()
at li.qubic.trainer.Helper.HardwareHelper.GetCPUCache()
2024-03-17 08:43:34 INFO AI Training Starting. Your Alias is RTX_3080_Ti
2024-03-17 08:43:34 INFO Waiting for task (0)
2024-03-17 08:43:35 INFO Trainer: cpu version 100.2 is starting.
2024-03-17 08:43:35 INFO Trainer: Version: AVX2
2024-03-17 08:43:35 INFO Trainer: Solution threshold: 44
2024-03-17 08:43:35 INFO Trainer: Accept score range [0,84] & [172,256]
2024-03-17 08:43:35 INFO Trainer: Neuron value limit: 0x10000000000
2024-03-17 08:43:35 INFO Trainer: Mining seed: ad04a287a144ba3f10e663d531908bde1b8eee712092903f485414dc22c8428b
2024-03-17 08:43:36 INFO E:100 | SOL: 0/0 | Try GYKP...ELQC | 4 it/s | 4 avg it/s
2024-03-17 08:43:37 INFO E:100 | SOL: 0/0 | Try GYKP...ELQC | 5 it/s | 4 avg it/s

I installed -> The runner on Windows also requires the VC Redistributable
I had last version Windows and Nvidia Driver

CPU is working correct Ryzen 9 7900X
GPU RTX 3080 Ti - I can't start mining on GPU

**Comment by davepl** [comment]
I also see this on a 7995WX/Ada6000 setup... and cannot mine GPU.

**Comment by christoph2005** [comment]
I have the same problem
I installed the prerequisites also: Latest Cuda, .Net 6, VC redistributable

> 
{
  "Settings": {
    "baseUrl": "https://mine.qubic.li/",
    "amountOfThreads": 12,
    "allowHwInfoCollect":true,
    "overwrites":{"CUDA":12},
    "accessToken": "",
    "alias": "********"
  }
}
> 

> 

2024-03-29 04:41:12     INFO    Starting Client 1.8.10.0
2024-03-29 04:41:12     INFO    Check for updates
2024-03-29 04:41:12     INFO    Your Client is up to date
System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
 ---> System.TypeLoadException
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(IntPtr, Type)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr)
   at System.Management.WmiNetUtilsHelper.LoadDelegate[TDelegate](TDelegate&, IntPtr, String)
   at System.Management.WmiNetUtilsHelper..cctor()
   --- End of inner exception stack trace ---
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type)
   at System.Management.ManagementPath.CreateWbemPath(String)
   at li.qubic.trainer.Helper.HardwareHelper.GetCPUCacheWindows()
   at li.qubic.trainer.Helper.HardwareHelper.GetCPUCache()
2024-03-29 04:41:13     INFO    AI Training Starting. Your Alias is ********
2024-03-29 04:41:13     INFO    Waiting for task (0)
2024-03-29 04:41:14     INFO    Trainer: cpu version 102.0 is starting.
2024-03-29 04:41:14     INFO    Trainer: Version: AVX2
2024-03-29 04:41:14     INFO    Trainer: Solution threshold: 43
2024-03-29 04:41:14     INFO    Trainer: Accept score range [0,42] & [128,256]
2024-03-29 04:41:14     INFO    Trainer: Neuron value limit: 0x1
2024-03-29 04:41:14     INFO    Trainer: Mining seed: d0043409e683de0e3ff516b2c35ecb99f4cf2318e88d7e1f394567e314393671
2024-03-29 04:41:15     INFO    E:102 | SOL: 0/0 | Try OKIN...QKPK  | 0 it/s | 0 avg it/s
2024-03-29 04:41:16     INFO    E:102 | SOL: 0/0 | Try OKIN...QKPK  | 0 it/s | 0 avg it/s

>

**Comment by jmachado45** [comment]
Hi, still no solution for this? Does anyone was able to bypass this issue?

Thank you
