### ISSUE TITLE
Error checking for updates: API checkupdate error: Unauthorized

### ISSUE THREAD

**Issue by Elsikan1** [qubic-li/client#60]
Hi, i have an error

2024-03-22 19:52:40     INFO    Starting Client 1.8.10.0
2024-03-22 19:52:41     INFO    Check for updates
2024-03-22 19:52:43     ERROR   Error Checking for updates: API CheckUpdate Error: Unauthorized
2024-03-22 19:52:43     ERROR   Feature Registration Request Failed(API Register Error: Unauthorized)

System.Exception: API Register Error: Unauthorized
   at li.qubic.trainer.Client.Register(TrainerRegisterRequest featureRequest)
   at li.qubic.trainer.Trainer.RegisterFeatures()
   at li.qubic.trainer.Client.Register(TrainerRegisterRequest featureRequest)
   at li.qubic.trainer.Trainer.RegisterFeatures()
2024-03-22 19:52:43     INFO    AI Training Starting. Your Alias is qubic.li Client
2024-03-22 19:52:43     INFO    Waiting for task (0)
API: Access Denied
2024-03-22 19:52:44     INFO    Waiting for task (598)

have an idea why please ?
Thanks ;)

**Comment by Elsikan1** [comment]
ok after rewrite my "accessToken" this error have disapear ;)

But an other problem arrived ^^

2024-03-22 20:27:11     INFO    Starting Client 1.8.10.0
2024-03-22 20:27:11     INFO    Check for updates
2024-03-22 20:27:13     INFO    Your Client is up to date
2024-03-22 20:27:13     INFO    AI Training Starting. Your Alias is qubic.li Client
2024-03-22 20:27:13     INFO    Waiting for task (0)
2024-03-22 20:27:15     INFO    Trainer: cpu version 101.2 is starting.
2024-03-22 20:27:15     INFO    Trainer: Version: Generic
2024-03-22 20:27:15     INFO    Trainer: Solution threshold: 42
2024-03-22 20:27:15     INFO    Trainer: Accept score range [0,86] & [170,256]
2024-03-22 20:27:15     INFO    Trainer: Neuron value limit: 0x1
2024-03-22 20:27:15     INFO    Trainer: Mining seed: ec5d8008b62b4195f09721e5c1d37d30601f4be9fd28a8392cc71144cb2e4c64
2024-03-22 20:27:15     INFO    Trainer: WARNING: Free number of hugepages is smaller than needed, have: 0 - want: 416 (52 x number of threads). Falling back to use malloc memory.
2024-03-22 20:27:15     INFO    Trainer: To add more hugepages, please run this command as root before starting the miner
2024-03-22 20:27:15     INFO    Trainer: /usr/sbin/sysctl -w vm.nr_hugepages=416
2024-03-22 20:27:15     INFO    Trainer: OR: /sbin/sysctl -w vm.nr_hugepages=416
2024-03-22 20:27:20     INFO    Trainer: cpu version 101.2 is starting.
2024-03-22 20:27:20     INFO    Trainer: Version: Generic
2024-03-22 20:27:20     INFO    Trainer: Solution threshold: 42
2024-03-22 20:27:20     INFO    Trainer: Accept score range [0,86] & [170,256]
2024-03-22 20:27:20     INFO    Trainer: Neuron value limit: 0x1
2024-03-22 20:27:20     INFO    Trainer: Mining seed: ec5d8008b62b4195f09721e5c1d37d30601f4be9fd28a8392cc71144cb2e4c64
2024-03-22 20:27:20     INFO    Trainer: WARNING: Free number of hugepages is smaller than needed, have: 0 - want: 416 (52 x number of threads). Falling back to use malloc memory.
2024-03-22 20:27:20     INFO    Trainer: To add more hugepages, please run this command as root before starting the miner

**Comment by Elsikan1** [comment]
ok after enter command for hugepages  /sbin/sysctl -w vm.nr_hugepages=416

i have a new problem ^^

2024-03-22 20:38:54     INFO    Starting Client 1.8.10.0
2024-03-22 20:38:54     INFO    Check for updates
2024-03-22 20:38:56     INFO    Your Client is up to date
2024-03-22 20:38:56     INFO    AI Training Starting. Your Alias is qubic.li Client
2024-03-22 20:38:56     INFO    Waiting for task (0)
2024-03-22 20:38:57     INFO    Trainer: cpu version 101.2 is starting.
2024-03-22 20:38:57     INFO    Trainer: Version: Generic
2024-03-22 20:38:57     INFO    Trainer: Solution threshold: 42
2024-03-22 20:38:57     INFO    Trainer: Accept score range [0,86] & [170,256]
2024-03-22 20:38:57     INFO    Trainer: Neuron value limit: 0x1
2024-03-22 20:38:57     INFO    Trainer: Mining seed: ec5d8008b62b4195f09721e5c1d37d30601f4be9fd28a8392cc71144cb2e4c64

this turn in loop ... an idea for help me please ?

**Comment by boylixiang** [comment]
My excavator is showing an error message. Do I need to wait?
、
API Register Error:serviceUnavailableat li.qubic.trainer.client.Register(TrainerRegisterRegat li.qubic.trainer.Trainer.RegisterFeatures()li.qubic.trainer.client.Register(TrainerRegisterRequatat li.qubic.trainer.Trainer.RegisterFeatures()Waiting for

**Comment by Bhy567** [comment]
I'm getting no sols but iv noticed in log file in miner I get ping api error service  unavailable  but the miner is still going any help please

**Comment by cdnbum88** [comment]
Same issue too
