### ISSUE TITLE
mine.qubic.li - down/ddos?

### ISSUE THREAD

**Issue by dominiaz** [qubic-li/client#61]
2024-03-23 06:22:46     INFO    Starting Client 1.8.10.0
2024-03-23 06:22:46     INFO    Check for updates
2024-03-23 06:22:55     ERROR   Error Checking for updates: API CheckUpdate Error: ServiceUnavailable
2024-03-23 06:23:03     ERROR   Feature Registration Request Failed(API Register Error: ServiceUnavailable)

System.Exception: API Register Error: ServiceUnavailable
   at li.qubic.trainer.Client.Register(TrainerRegisterRequest featureRequest)
   at li.qubic.trainer.Trainer.RegisterFeatures()
   at li.qubic.trainer.Client.Register(TrainerRegisterRequest featureRequest)
   at li.qubic.trainer.Trainer.RegisterFeatures()
2024-03-23 06:23:03     INFO    AI Training Starting. Your Alias is qubic20
2024-03-23 06:23:03     INFO    Waiting for task (0)
API Error: API Error: ServiceUnavailable
2024-03-23 06:23:11     ERROR   Failed loading Task. API Error: ServiceUnavailable

What is happening with the pool?

**Comment by ephebus** [comment]
No payout from last epoch yet either.
